var arrLang = {
        'en': {

            //header.php
            'vaardigheden': 'Skills',
            'over': 'About us ',
            'partners': 'Partners',
            'email': 'E-mail',
            'telefoon': 'Phone',
            'settings': 'Settings',
            'kleuren': 'Color Scheme',
            'business': 'Business',
            'friendly': 'Friendly',
            'warm': 'Warm',
            'taal': 'Language',
            'slogan': 'Because with teamwork you get the furthest!',
            'start': 'Start now',
            //home.php
            'zie': 'See more',
            'prof': 'Professionality',
            'kennis': 'The knowledge that we have to make what you need.',
            'designtitle': '',
            'designtekst': '',
            'proftitle': '',
            'proftekst': '',
            'wie': 'Who are we?',
            'team': 'The Team',
            'Email sturen': 'Send email:',
            'versturen': 'Send your message',
            'voornaam': 'Forname',
            'achternaam': 'Lastname',
            'herhaal': 'Repeat Email',
            'bericht': 'Message',
            //footer.php
            'vragen': 'Frequently Asked Questions',
            'domein': 'Can I buy a domain through INITIATIVE?',
            'hosten': 'Is it possible to host my website through INITIATIVE?',
            'ergens anders': 'What if I want to host my website somewhere else?',
            'bekijk': 'View more',
            'bellen': 'I would like to call',
            'email sturen': 'I would like to send an email',
            'support email': 'I want to send a support email',
            'partnership': 'I would like to discuss a partnership',
            'zaken doen': 'I would like to do business',
            'copyright': 'Copyright © 2020 INITIATIVE. All rights reserved.'


        },
        'nl': {

            //header.php
            'vaardigheden': 'Vaardigheden',
            'over': 'Over ons',
            'partners': 'Partners',
            'email': 'Email',
            'telefoon': 'Telefoon',
            'settings': 'Instellingen',
            'kleuren': 'Kleuren Schema',
            'business': 'Zakelijk',
            'friendly': 'Vriendelijk',
            'warm': 'Warm',
            'taal': 'Taal',
            'slogan': 'Want met teamwork kom je het verst!',
            'start': 'Start meteen',
            //home.php
            'zie': 'Zie meer',
            'prof': 'Professionaliteit',
            'kennis': 'De kennis die wij bezitten om te maken wat jij nodig hebt.',
            'wie': 'Wie zijn wij?',
            'team': 'Het Team',
            'Email sturen': 'Email sturen:',
            'versturen': 'Bericht versturen',
            'voornaam': 'Voornaam',
            'achternaam': 'Achternaam',
            'herhaal': 'Herhaal Email',
            'bericht': 'Bericht',
            //footer.php
            'vragen': 'Veel gestelde vragen',
            'domein': 'Kan ik een domein kopen via INITIATIVE?',
            'hosten': 'Is het mogelijk om mijn website te hosten via INITIATIVE?',
            'ergens anders': 'Wat als ik mijn website ergens anders wil hosten?',
            'bekijk': 'Bekijk meer',
            'bellen': 'Ik wil graag bellen',
            'email sturen': 'Ik wil graag een email sturen',
            'support email': 'Ik wil een support email sturen',
            'partnership': 'Ik zou een partnership willen bespreken',
            'zaken doen': 'Ik zou graag zaken willen doen',
            'copyright': 'Auteursrechten © 2020 INITIATIVE. Alle rechten voorbehouden.'

        },
        'de': {

            //header.php
            'vaardigheden': 'Fähigkeiten',
            'over': 'über uns',
            'partners': 'Partner',
            'email': 'E-Mail',
            'telefoon': 'Telefon',
            'settings': 'Institutionen',
            'kleuren': 'Farbschema',
            'business': 'Sachlich',
            'friendly': 'Freundlich',
            'warm': 'Warm',
            'taal': 'Sprache',
            'slogan': 'Denn mit Teamwork machen Sie Erfolg!',
            'start': 'Starte sofort',
            //home.php
            'zie': 'Mehr sehen',
            'prof': 'Professionalität',
            'kennis': 'Das Wissen, das wir besitzen, um das zu machen, was Sie brauchen.',
            'wie': 'Wer wir sind?',
            'team': 'Das Team',
            'Email sturen': 'E-Mail senden:',
            'versturen': 'Nachricht senden',
            'voornaam': 'Vorname',
            'achternaam': 'Nachname',
            'herhaal': 'Email wiederholen',
            'bericht': 'Nachricht',
            //footer.php
            'vragen': 'Häufig gestellte fragen',
            'domein': 'Kann ich über INITIATIVE eine Domain kaufen?',
            'hosten': 'Ist es möglich, meine Website über INITIATIVE zu hosten?',
            'ergens anders': 'Was ist, wenn ich meine Website woanders hosten möchte?',
            'bekijk': 'Was ist, wenn ich meine Website woanders hosten möchte?',
            'bellen': 'Ich würde gerne anrufen',
            'email sturen': 'Ich würde gerne ein E-Mail senden',
            'support email': 'Ich möchte eine Support-E-Mail senden',
            'partnership': 'Ich möchte eine Partnerschaft besprechen',
            'zaken doen': 'Ich würde gerne Geschäfte machen',
            'copyright': 'Urheberrecht  © 2020 INITIATIVE. Alle rechte vorbehalten.'
        }
    };